name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Add conda-forge
      run: conda config --env --add channels conda-forge
    - name: Install dependencies
      run: |
        conda env update --file env.yml --name base
        conda install pytest
#     - name: Lint with flake8
#       run: |
#         conda install flake8
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: env summary
      run: conda list
    - name: install qubekit
      run: |
        pip install .
    - name: pytest
      run: |
        python -c "import pytest; from fegrow.testing import loc ; pytest.main([loc])"
    - name: Run tutorial.py
      run: |
        cd notebooks
        obabel sarscov2/lig.pdb -O sarscov2/coreh.sdf -p 7
        wget -nc https://files.rcsb.org/download/7L10.pdb        
        python .tutorial.py
