name: CI

on: [pull_request]

jobs:
  tests:
    name: Test on ${{ matrix.os }}, 🐍=${{ matrix.python-version }}, Program=${{ matrix.conda-env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: ["3.10", "3.11"]
      max-parallel: 5

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Create Environment
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: env summary
      run: conda list

    - name: dry install fegrow
      run: pip install --dry-run .

    - name: install fegrow
      run: pip install .

    - name: install pytest
      run: mamba install pytest
      shell: micromamba-shell {0}

    - name: pytest
      run: pytest fegrow/testing

    - name: Run tutorial.py
      run: |
        cd notebooks
        obabel sarscov2/lig.pdb -O sarscov2/coreh.sdf -p 7
        wget -nc https://files.rcsb.org/download/7L10.pdb        
        python .tutorial.py
