name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Create Environment
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: test
        environment-file: env.yml
        python-version: 3.8
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true
        mamba-version: "*"
        miniforge-version: latest
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: env summary
      run: conda list
    - name: install fegrow
      run: |
        pip install .
    - name: pytest
      run: |
        python -c "import pytest; from fegrow.testing import loc ; pytest.main([loc])"
    - name: Run tutorial.py
      run: |
        cd notebooks
        obabel sarscov2/lig.pdb -O sarscov2/coreh.sdf -p 7
        wget -nc https://files.rcsb.org/download/7L10.pdb        
        python -q -X faulthandler .tutorial.py
