name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: env.yaml
        environment-name: fegrow
    - name: env summary
      shell: bash -l {0}
      run: conda list
    - name: install fegrow
      shell: bash -l {0}
      run: |
        pip install .
    - name: install pytest
      shell: bash -l {0}
      run: mamba install pytest
    - name: which python
      shell: bash -l {0}
      run: which python
    - name: pytest
      shell: bash -l {0}
      run: python -c "import pytest; from fegrow.testing import loc ; pytest.main([loc])"
    - name: Run tutorial.py
      shell: bash -l {0}
      run: |
        cd notebooks
        obabel sarscov2/lig.pdb -O sarscov2/coreh.sdf -p 7
        wget -nc https://files.rcsb.org/download/7L10.pdb        
        python -q -X faulthandler .tutorial.py
