name: Publish Docs to branch

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create FEgrow Environment
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        create-args: >-
          python='3.10'

    - name: Install FEgrow
      run: pip install --no-deps .

    - name: Add docs-generating packages
      run: mamba env update --file docs/environment.yml

    - name: Determine Version
      shell: bash
      run: |
        if [ "$GITHUB_REF" = "refs/heads/master" ]; then
          echo "VERSION=latest" >> $GITHUB_ENV
        elif [ "${GITHUB_REF#refs/tags/}" != "$GITHUB_REF" ]; then
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "VERSION=$VERSION stable" >> $GITHUB_ENV
        else
          echo "Invalid ref: $GITHUB_REF"
          exit 1
        fi
        echo "Docs version: $VERSION" 

    - name: Build and Deploy Documentation
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git config --global --add safe.directory "$PWD"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

        git fetch --all --prune
        
        mike deploy --push --update-aliases $VERSION
