name: Nice

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install black ruff
    - name: Checking code formatting with black
      run: |
        black --check $(git ls-files '*.py')
    - name: Lint with ruff
      run: |
        ruff check
